In [1]:
import pandas as pd
import numpy as np
import random
import warnings
warnings.filterwarnings(action = 'ignore')
random.seed(0)

In [2]:
df = pd.read_csv("/kaggle/input/ibm-telco-11-1-3/telco.csv", engine = "python")

In [3]:
df.head()

Customer ID  Gender  Age Under 30 Senior Citizen Married Dependents  \
0  8779-QRDMV    Male   78       No            Yes      No         No   
1  7495-OOKFY  Female   74       No            Yes     Yes        Yes   
2  1658-BYGOY    Male   71       No            Yes      No        Yes   
3  4598-XLKNJ  Female   78       No            Yes     Yes        Yes   
4  4846-WHAFZ  Female   80       No            Yes     Yes        Yes   

   Number of Dependents        Country       State  ...  \
0                     0  United States  California  ...   
1                     1  United States  California  ...   
2                     3  United States  California  ...   
3                     1  United States  California  ...   
4                     1  United States  California  ...   

  Total Extra Data Charges  Total Long Distance Charges  Total Revenue  \
0                       20                         0.00          59.65   
1                        0                       390.80        1024.10   
2                        0                       203.94        1910.88   
3                        0                       494.00        2995.07   
4                        0                       234.21        3102.36   

   Satisfaction Score  Customer Status Churn Label Churn Score  CLTV  \
0                   3          Churned         Yes          91  5433   
1                   3          Churned         Yes          69  5302   
2                   2          Churned         Yes          81  3179   
3                   2          Churned         Yes          88  5337   
4                   2          Churned         Yes          67  2793   

    Churn Category                  Churn Reason  
0       Competitor  Competitor offered more data  
1       Competitor  Competitor made better offer  
2       Competitor  Competitor made better offer  
3  Dissatisfaction     Limited range of services  
4            Price            Extra data charges  

[5 rows x 50 columns]

In [4]:
p1 = 'Offer'
p2 = 'Phone Service'
p3 = 'Internet Service'
p4 = 'Device Protection Plan'
p5 = 'Premium Tech Support'

cid = 'Customer ID'

In [5]:
df['p1'] = df[p1].apply(lambda x: 0 if pd.isnull(x) else 1)
df['p2'] = df[p2].apply(lambda x: 1 if x=='Yes' else 0)
df['p3'] = df[p3].apply(lambda x: 1 if x=='Yes' else 0)
df['p4'] = df[p4].apply(lambda x: 1 if x=='Yes' else 0)
df['p5'] = df[p5].apply(lambda x: 1 if x=='Yes' else 0)

In [6]:
df['p0'] = df.apply(lambda x: (x['p1']==0) & (x['p2']==0) & (x['p3']==0) & (x['p4']==0) & (x['p5']==0), axis=1)

In [7]:
p1_array = df['p1'].values
p2_array = df['p2'].values
p3_array = df['p3'].values
p4_array = df['p4'].values
p5_array = df['p5'].values
p0_array = df['p0'].values
p1_count = sum(p1_array)
p2_count = sum(p2_array)
p3_count = sum(p3_array)
p4_count = sum(p4_array)
p5_count = sum(p5_array)
p0_count = sum(p0_array)

In [8]:
p1_array

array([0, 1, 1, ..., 0, 0, 0])

In [9]:
p1_count

3166

In [10]:
df_len = len(df)

In [11]:
P = {}
P['p1'] = p1_count/df_len
P['p2'] = p2_count/df_len
P['p3'] = p3_count/df_len
P['p4'] = p4_count/df_len
P['p5'] = p5_count/df_len
P['p0'] = p0_count/df_len

In [12]:
P

{'p1': 0.4495243504188556,
 'p2': 0.9031662643759761,
 'p3': 0.7833309669175067,
 'p4': 0.3438875479199205,
 'p5': 0.2902172369728809,
 'p0': 0.0}

In [13]:
p1_array.shape

(7043,)

In [14]:
p1_array.T.shape

(7043,)

In [15]:
p1_array

array([0, 1, 1, ..., 0, 0, 0])

In [16]:
p1_array[:, np.newaxis]

array([[0],
       [1],
       [1],
       ...,
       [0],
       [0],
       [0]])

In [17]:
p1_array[:, np.newaxis].shape

(7043, 1)

In [18]:
ones_array = np.ones(df_len)
ones_array

array([1., 1., 1., ..., 1., 1., 1.])

In [19]:
ones_matrix = ones_array[:, np.newaxis]
ones_matrix

array([[1.],
       [1.],
       [1.],
       ...,
       [1.],
       [1.],
       [1.]])

In [20]:
ones_matrix.T

array([[1., 1., 1., ..., 1., 1., 1.]])

In [21]:
p1_array[:, np.newaxis] * (ones_matrix.T)

array([[0., 0., 0., ..., 0., 0., 0.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [22]:
p1_array[:, np.newaxis] * np.ones(df_len)

array([[0., 0., 0., ..., 0., 0., 0.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [23]:
ones_array = np.ones(df_len)
ones_row_matrix = ones_array[:, np.newaxis].T
p1_matrix = (p1_array[:, np.newaxis] * ones_row_matrix)>0
p2_matrix = (p2_array[:, np.newaxis] * ones_row_matrix)>0
p3_matrix = (p3_array[:, np.newaxis] * ones_row_matrix)>0
p4_matrix = (p4_array[:, np.newaxis] * ones_row_matrix)>0
p5_matrix = (p5_array[:, np.newaxis] * ones_row_matrix)>0
p0_matrix = (p0_array[:, np.newaxis] * ones_row_matrix)>0

p_matrix = {}
p_matrix[0] = p0_matrix
p_matrix[1] = p1_matrix
p_matrix[2] = p2_matrix
p_matrix[3] = p3_matrix
p_matrix[4] = p4_matrix
p_matrix[5] = p5_matrix

In [24]:
# delta_CLTV_matrix
CLTV_array = df['CLTV'].values
CLTV_matrix = CLTV_array[:, np.newaxis] * ones_row_matrix
delta_CLTV_matrix = CLTV_matrix - CLTV_matrix.T
delta_CLTV_matrix = delta_CLTV_matrix>0
delta_CLTV_matrix = delta_CLTV_matrix.astype(int)
delta_CLTV_matrix

array([[0, 1, 1, ..., 0, 1, 1],
       [0, 0, 1, ..., 0, 1, 1],
       [0, 0, 0, ..., 0, 1, 0],
       ...,
       [1, 1, 1, ..., 0, 1, 1],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 1, ..., 0, 1, 0]])

In [25]:
# delta_ChurnScore_matrix
ChurnScore_array = df['Churn Score'].values
ChurnScore_matrix = ChurnScore_array[:, np.newaxis] * ones_row_matrix
delta_ChurnScore_matrix = ChurnScore_matrix - ChurnScore_matrix.T
delta_ChurnScore_matrix = delta_ChurnScore_matrix<0
delta_ChurnScore_matrix = delta_ChurnScore_matrix.astype(int)
delta_ChurnScore_matrix

array([[0, 0, 0, ..., 0, 0, 0],
       [1, 0, 1, ..., 1, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       ...,
       [1, 0, 1, ..., 0, 0, 0],
       [1, 1, 1, ..., 1, 0, 0],
       [1, 1, 1, ..., 1, 1, 0]])

In [26]:
#delta_SatisfactionScore_matrix
SatisfactionScore_array = df['Satisfaction Score'].values
SatisfactionScore_matrix = SatisfactionScore_array[:, np.newaxis] * ones_row_matrix
delta_SatisfactionScore_matrix = SatisfactionScore_matrix - SatisfactionScore_matrix.T
delta_SatisfactionScore_matrix = delta_SatisfactionScore_matrix>0
delta_SatisfactionScore_matrix = delta_SatisfactionScore_matrix.astype(int)
delta_SatisfactionScore_matrix

array([[0, 0, 1, ..., 0, 0, 0],
       [0, 0, 1, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [1, 1, 1, ..., 0, 0, 0],
       [1, 1, 1, ..., 0, 0, 0],
       [1, 1, 1, ..., 0, 0, 0]])

In [27]:
d = {}
d['x'] = delta_CLTV_matrix
d['y'] = delta_ChurnScore_matrix
d['z'] = delta_SatisfactionScore_matrix

In [28]:
count = {}
for var in ['x', 'y', 'z']:
    D = d[var]
    for i in range(6):
        count[f"d{var} ∩ p{i}"] = np.sum(D & p_matrix[i], axis=0)
        P[f"d{var} ∩ p{i}"] = count[f"d{var} ∩ p{i}"]/df_len
        count[f"d{var} ∩ p{i}"] = np.where(count[f"d{var} ∩ p{i}"]>0, count[f"d{var} ∩ p{i}"], -1)
        for j in range(6):
            count[f"d{var} ∩ p{i} ∩ p{j}"] = np.sum(D & p_matrix[i] & p_matrix[j], axis=0)
            P[f"p{j} | d{var} ∩ p{i}"] = count[f"d{var} ∩ p{i} ∩ p{j}"]/count[f"d{var} ∩ p{i}"]
            #P[f"p{j} | d{var} ∩ p{i}"] = np.where(P[f"p{j} | d{var} ∩ p{i}"]>0, P[f"p{j} | d{var} ∩ p{i}"], 0.5)

In [29]:
for var in 'xyz':
    for i in range(6):
        for j in range(6):
            if P[f'p{j}']==0:
                P[f'd{var} ∩ p{i} | p{j}'] = 0.5 + np.abs(np.random.randn(df_len)*0.01)
            else:
                P[f'd{var} ∩ p{i} | p{j}'] = P[f"p{j} | d{var} ∩ p{i}"]*P[f'd{var} ∩ p{i}'] / P[f'p{j}']
                P[f'd{var} ∩ p{i} | p{j}'] = np.where(P[f'd{var} ∩ p{i} | p{j}']>=0, P[f'd{var} ∩ p{i} | p{j}'], 0.5)
                P[f'd{var} ∩ p{i} | p{j}'] = P[f'd{var} ∩ p{i} | p{j}']

In [30]:
for var in 'xyz':
    for i in range(6):
        for j in range(6):
            alpha = np.random.uniform(0, 0.1, df_len)
            df[f"{var.upper()}{i}{j}"] = P[f'd{var} ∩ p{j} | p{i}']*(1-alpha) + alpha*np.random.uniform(0,1, df_len)

In [31]:
df.to_csv("/kaggle/working/Data_with_probabilities.csv", index=None)